import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

export default defineSchema({
  users: defineTable({
    firstName: v.string(),
    lastName: v.string(),
    email: v.string(),
    role: v.string(),
    department: v.string(),
    position: v.string(),
    hireDate: v.string(),
    avatar: v.string(),
    // New fields from CSV
    leader: v.optional(v.string()),
    access: v.optional(v.string()),
    cv: v.optional(v.string()),
    seniority: v.optional(v.string()),
    industries: v.optional(v.string()),
    linkedin: v.optional(v.string()),
    experienceStarted: v.optional(v.string()),
    joinedCieden: v.optional(v.string()),
    inCieden: v.optional(v.string()),
    totalExperience: v.optional(v.string()),
    english: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
  }),
  goals: defineTable({
    userId: v.id("users"),
    title: v.string(),
    description: v.string(),
    goalType: v.string(),
    priority: v.string(),
    status: v.string(),
    progress: v.number(),
    deadline: v.string(),
    link: v.optional(v.string()),
    tags: v.array(v.string()),
  }),
  feedback: defineTable({
    fromUserId: v.id("users"),
    toUserId: v.id("users"),
    rating: v.number(),
    category: v.string(),
    comment: v.string(),
    date: v.string(),
    status: v.string(),
    isAnonymous: v.boolean(),
  }),
  performanceCycles: defineTable({
    name: v.string(),
    description: v.string(),
    startDate: v.string(),
    endDate: v.string(),
    status: v.string(),
    participants: v.number(),
    completedReviews: v.number(),
    averageRating: v.number(),
  }),
});

export const createUser = mutation({
  args: {
    clerkId: v.string(),
    email: v.string(),
    firstName: v.string(),
    lastName: v.string(),
    role: v.union(v.literal("employee"), v.literal("manager"), v.literal("admin")),
    department: v.string(),
    position: v.string(),
    hireDate: v.string(),
    managerId: v.optional(v.id("users")),
    avatar: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const existingUser = await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", args.clerkId))
      .first();

    if (existingUser) {
      return existingUser._id;
    }

    const userId = await ctx.db.insert("users", {
      ...args,
      isActive: true,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });

    return userId;
  },
});

export const getUserByClerkId = query({
  args: { clerkId: v.string() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("users")
      .withIndex("by_clerk_id", (q) => q.eq("clerkId", args.clerkId))
      .first();
  },
});

export const getUserById = query({
  args: { userId: v.id("users") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.userId);
  },
});

export const getUsersByManager = query({
  args: { managerId: v.id("users") },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("users")
      .withIndex("by_manager", (q) => q.eq("managerId", args.managerId))
      .collect();
  },
});

export const getAllUsers = query({
  handler: async (ctx) => {
    return await ctx.db.query("users").collect();
  },
});

export const updateUser = mutation({
  args: {
    userId: v.id("users"),
    firstName: v.optional(v.string()),
    lastName: v.optional(v.string()),
    role: v.optional(v.union(v.literal("employee"), v.literal("manager"), v.literal("admin"))),
    department: v.optional(v.string()),
    position: v.optional(v.string()),
    managerId: v.optional(v.id("users")),
    avatar: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const { userId, ...updates } = args;
    await ctx.db.patch(userId, {
      ...updates,
      updatedAt: Date.now(),
    });
  },
});

export const deleteUser = mutation({
  args: { userId: v.id("users") },
  handler: async (ctx, args) => {
    await ctx.db.delete(args.userId);
  },
});

export const seedCiedenTeam = mutation({
  handler: async (ctx) => {
    // Очищаємо існуючі дані
    const existingUsers = await ctx.db.query("users").collect();
    for (const user of existingUsers) {
      await ctx.db.delete(user._id);
    }

    const ciedenTeam = [
      {
        clerkId: "cieden_yuriy",
        email: "yuriy@cieden.com",
        firstName: "Yuriy",
        lastName: "Mykhasyak",
        role: "admin" as const,
        department: "Leadership",
        position: "CEO & Co-founder",
        hireDate: "2020-01-01",
        avatar: "/team/yuriy-mykhasyak.jpg",
      },
      {
        clerkId: "cieden_iryna",
        email: "iryna@cieden.com",
        firstName: "Iryna",
        lastName: "Serednia",
        role: "admin" as const,
        department: "Design",
        position: "Design Director, Co-founder",
        hireDate: "2020-01-01",
        avatar: "/team/iryna-serednia.jpg",
      },
      {
        clerkId: "cieden_kateryna",
        email: "kateryna@cieden.com",
        firstName: "Kateryna",
        lastName: "Zavertailo",
        role: "manager" as const,
        department: "Sales",
        position: "Sales Manager",
        hireDate: "2021-03-15",
        avatar: "/team/kateryna-zavertailo.jpg",
      },
      {
        clerkId: "cieden_roman",
        email: "roman@cieden.com",
        firstName: "Roman",
        lastName: "Kaminechny",
        role: "manager" as const,
        department: "Design",
        position: "Head of Design Department",
        hireDate: "2021-06-01",
        avatar: "",
      },
      {
        clerkId: "cieden_anastasiya",
        email: "anastasiya@cieden.com",
        firstName: "Anastasiya",
        lastName: "Mudryk",
        role: "manager" as const,
        department: "Product Management",
        position: "Head of PM/BA",
        hireDate: "2021-08-01",
        avatar: "",
      },
      {
        clerkId: "cieden_olesia",
        email: "olesia@cieden.com",
        firstName: "Olesia",
        lastName: "Havryshko",
        role: "employee" as const,
        department: "Product Management",
        position: "Product Manager/Business Analyst",
        hireDate: "2021-01-15",
        avatar: "",
      },
      {
        clerkId: "cieden_tetiana_b",
        email: "tetiana.b@cieden.com",
        firstName: "Tetiana",
        lastName: "Bondarchuk",
        role: "employee" as const,
        department: "Product Management",
        position: "Product Manager/Business Analyst",
        hireDate: "2021-02-01",
        avatar: "",
      },
      {
        clerkId: "cieden_yulia",
        email: "yulia@cieden.com",
        firstName: "Yulia",
        lastName: "Mahera",
        role: "employee" as const,
        department: "Product Management",
        position: "Product Manager/Business Analyst",
        hireDate: "2021-03-01",
        avatar: "",
      },
      {
        clerkId: "cieden_andrew",
        email: "andrew@cieden.com",
        firstName: "Andrew",
        lastName: "Sapkowski",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-04-01",
        avatar: "",
      },
      {
        clerkId: "cieden_denis",
        email: "denis@cieden.com",
        firstName: "Denis",
        lastName: "Dudar",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-05-01",
        avatar: "",
      },
      {
        clerkId: "cieden_valentyn",
        email: "valentyn@cieden.com",
        firstName: "Valentyn",
        lastName: "Skliarov",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-06-01",
        avatar: "",
      },
      {
        clerkId: "cieden_daria",
        email: "daria@cieden.com",
        firstName: "Daria",
        lastName: "Novosiadla",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-07-01",
        avatar: "",
      },
      {
        clerkId: "cieden_tetiana_z",
        email: "tetiana.z@cieden.com",
        firstName: "Tetiana",
        lastName: "Zakus",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-08-01",
        avatar: "",
      },
      {
        clerkId: "cieden_maksym_g",
        email: "maksym.g@cieden.com",
        firstName: "Maksym",
        lastName: "Gozhelsky",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-09-01",
        avatar: "",
      },
      {
        clerkId: "cieden_oksana",
        email: "oksana@cieden.com",
        firstName: "Oksana",
        lastName: "Veskera",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-10-01",
        avatar: "",
      },
      {
        clerkId: "cieden_demian",
        email: "demian@cieden.com",
        firstName: "Demian",
        lastName: "Peretiatko",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-11-01",
        avatar: "",
      },
      {
        clerkId: "cieden_marta",
        email: "marta@cieden.com",
        firstName: "Marta",
        lastName: "Kacharaba",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2021-12-01",
        avatar: "",
      },
      {
        clerkId: "cieden_iryna_m",
        email: "iryna.m@cieden.com",
        firstName: "Iryna",
        lastName: "Mykytenko",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-01-01",
        avatar: "",
      },
      {
        clerkId: "cieden_volodymyr",
        email: "volodymyr@cieden.com",
        firstName: "Volodymyr",
        lastName: "Merlenko",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-02-01",
        avatar: "",
      },
      {
        clerkId: "cieden_iryna_t",
        email: "iryna.t@cieden.com",
        firstName: "Iryna",
        lastName: "Tanavska",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-03-01",
        avatar: "",
      },
      {
        clerkId: "cieden_yuliia",
        email: "yuliia@cieden.com",
        firstName: "Yuliia",
        lastName: "Braslavska",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-04-01",
        avatar: "",
      },
      {
        clerkId: "cieden_vladyslav",
        email: "vladyslav@cieden.com",
        firstName: "Vladyslav",
        lastName: "Pianov",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-05-01",
        avatar: "",
      },
      {
        clerkId: "cieden_maksym_v",
        email: "maksym.v@cieden.com",
        firstName: "Maksym",
        lastName: "Vertsanov",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-06-01",
        avatar: "",
      },
      {
        clerkId: "cieden_khrystyna",
        email: "khrystyna@cieden.com",
        firstName: "Khrystyna",
        lastName: "Nych",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-07-01",
        avatar: "",
      },
      {
        clerkId: "cieden_illia",
        email: "illia@cieden.com",
        firstName: "Illia",
        lastName: "Suprun",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-08-01",
        avatar: "",
      },
      {
        clerkId: "cieden_dmytro",
        email: "dmytro@cieden.com",
        firstName: "Dmytro",
        lastName: "Chyzh",
        role: "employee" as const,
        department: "Design",
        position: "Product Designer",
        hireDate: "2022-09-01",
        avatar: "",
      },
      {
        clerkId: "cieden_bohdana",
        email: "bohdana@cieden.com",
        firstName: "Bohdana",
        lastName: "Levochko",
        role: "employee" as const,
        department: "Sales",
        position: "Lead Generation / Account Manager",
        hireDate: "2021-09-01",
        avatar: "",
      },
      {
        clerkId: "cieden_taras",
        email: "taras@cieden.com",
        firstName: "Taras",
        lastName: "Kunanets",
        role: "employee" as const,
        department: "Sales",
        position: "Lead Generation Manager",
        hireDate: "2021-10-01",
        avatar: "",
      },
      {
        clerkId: "cieden_daya",
        email: "daya@cieden.com",
        firstName: "Daya",
        lastName: "Danyliv",
        role: "employee" as const,
        department: "Design",
        position: "Graphic Designer",
        hireDate: "2021-11-01",
        avatar: "",
      },
      {
        clerkId: "cieden_tamara",
        email: "tamara@cieden.com",
        firstName: "Tamara",
        lastName: "Zhostka",
        role: "employee" as const,
        department: "Marketing",
        position: "Marketing Manager",
        hireDate: "2021-12-01",
        avatar: "",
      },
      {
        clerkId: "cieden_tetiana_k",
        email: "tetiana.k@cieden.com",
        firstName: "Tetiana",
        lastName: "Korol",
        role: "employee" as const,
        department: "Marketing",
        position: "Marketing Manager",
        hireDate: "2022-01-01",
        avatar: "",
      },
      {
        clerkId: "cieden_natalia",
        email: "natalia@cieden.com",
        firstName: "Natalia",
        lastName: "Antonyshyn",
        role: "employee" as const,
        department: "Finance",
        position: "Accountant",
        hireDate: "2021-08-01",
        avatar: "",
      },
      {
        clerkId: "cieden_katya",
        email: "katya@cieden.com",
        firstName: "Katya",
        lastName: "Gorodova",
        role: "manager" as const,
        department: "HR",
        position: "Head of Talent Management Department",
        hireDate: "2021-07-01",
        avatar: "",
      },
      {
        clerkId: "cieden_iryna_mykh",
        email: "iryna.mykh@cieden.com",
        firstName: "Iryna",
        lastName: "Mykhasyak",
        role: "employee" as const,
        department: "HR",
        position: "Recruiter",
        hireDate: "2021-09-01",
        avatar: "",
      },
    ];

    const userIds = [];
    
    for (const member of ciedenTeam) {
      const existingUser = await ctx.db
        .query("users")
        .withIndex("by_clerk_id", (q) => q.eq("clerkId", member.clerkId))
        .first();

      if (!existingUser) {
        const userId = await ctx.db.insert("users", {
          ...member,
          isActive: true,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        });
        userIds.push(userId);
      }
    }

    return userIds;
  },
});

export const seedRealCiedenTeam = mutation({
  args: {},
  handler: async (ctx) => {
    // Delete all existing users first
    const existingUsers = await ctx.db.query("users").collect();
    for (const user of existingUsers) {
      await ctx.db.delete(user._id);
    }

    // Real Cieden team data from CSV
    const realCiedenTeam = [
      {
        firstName: "Andrii",
        lastName: "Prokopyshyn",
        email: "andrii.prokopyshyn@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Anastasiya Mudryk",
        access: "Employee",
        cv: "https://drive.google.com/file/d/15wge4YXsQ5SnZf3W3b7czqhwYuE0mCXp/view?usp=drive_link",
        seniority: "Senior",
        industries: "",
        linkedin: "",
        experienceStarted: "15/8/18",
        joinedCieden: "",
        inCieden: "",
        totalExperience: "",
        english: "B1",
        isActive: true,
      },
      {
        firstName: "Bohdan",
        lastName: "Borys",
        email: "bohdan.borys@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Middle",
        industries: "",
        linkedin: "",
        experienceStarted: "",
        joinedCieden: "",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Demian",
        lastName: "Peretiatko",
        email: "demian.peretiatko@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "https://drive.google.com/file/d/13czCTca2MYPsbV4ssgzwJrC6CttKlReK/view?usp=drive_link",
        seniority: "Senior",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/demian-peretiatko-3a4054191",
        experienceStarted: "11/1/18",
        joinedCieden: "11/10/21",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Denis",
        lastName: "Dudar",
        email: "denis.dudar@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Tetiana Bondarchuk",
        access: "Employee",
        cv: "https://drive.google.com/file/d/1FlzUparfJMYjtLM-sRk_9suM0UfYW9On/view?usp=drive_link",
        seniority: "Senior",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/denis-dudar-88274a164?trk=people-guest_people_search-card",
        experienceStarted: "1/12/16",
        joinedCieden: "13/11/18",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Dmytro",
        lastName: "Chyzh",
        email: "dima.chyzh@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "",
        joinedCieden: "",
        inCieden: "",
        totalExperience: "",
        english: "A1",
        isActive: true,
      },
      {
        firstName: "Illia",
        lastName: "Suprun",
        email: "illia.suprun@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Str. Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/illia-suprun",
        experienceStarted: "3/9/18",
        joinedCieden: "13/3/23",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Iryna",
        lastName: "Mykytenko",
        email: "iryna.mykytenko@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "https://drive.google.com/file/d/1cQRE0ZqHSsQndxfxGrlqQPT4S-2j3dIF/view?usp=drive_link",
        seniority: "Senior",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/iryna-mykytenko?trk=people-guest_people_search-card",
        experienceStarted: "1/5/19",
        joinedCieden: "7/4/21",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Iryna",
        lastName: "Tanavska",
        email: "iryna.tanavska@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Tetiana Bondarchuk",
        access: "Employee",
        cv: "",
        seniority: "Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/iryna-tanavska/uk",
        experienceStarted: "2017",
        joinedCieden: "18/3/22",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Karyna",
        lastName: "Khmelyk",
        email: "karyna.khmelyk@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "https://drive.google.com/file/d/124sQ5_wTnJY6Agke91Tdumd60_sSIlaf/view?usp=drive_link",
        seniority: "Senior",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/karyna-halavur",
        experienceStarted: "1/4/17",
        joinedCieden: "15/11/23",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Khrystyna",
        lastName: "Nych",
        email: "khrystyna.nych@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "https://drive.google.com/file/d/1gS6IzdsvqAb2tGj0O-uDbUtth9Dh1CYH/view?usp=drive_link",
        seniority: "Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/khrystyna-nych-032486190",
        experienceStarted: "1/3/20",
        joinedCieden: "6/2/23",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Maksym",
        lastName: "Gozhelsky",
        email: "maksym.gozhelsky@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Yuliia Mahera",
        access: "Employee",
        cv: "https://drive.google.com/file/d/1hSal3amuP7rrekjneozlPhiml0dGnxuK/view?usp=drive_link",
        seniority: "Str. Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/maksym-gozhelsky-983410190",
        experienceStarted: "1/10/18",
        joinedCieden: "12/4/21",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Maksym",
        lastName: "Vertsanov",
        email: "maksym.vertsanov@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Tetiana Bondarchuk",
        access: "Employee",
        cv: "",
        seniority: "Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/vertsanovmaksim",
        experienceStarted: "2019",
        joinedCieden: "15/5/23",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Marta",
        lastName: "Kacharaba",
        email: "marta.kacharaba@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Anastasiya Mudryk",
        access: "Employee",
        cv: "",
        seniority: "Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/marta-kacharaba-715bb2162",
        experienceStarted: "12/1/17",
        joinedCieden: "1/12/21",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Mykola",
        lastName: "Chumak",
        email: "mykola.chumak@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Middle",
        industries: "",
        linkedin: "https://www.linkedin.com/in/m-chumak-desigr",
        experienceStarted: "1/10/14",
        joinedCieden: "19/5/25",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Nazar",
        lastName: "Vasylyshyn",
        email: "nazar.vasylyshyn@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Senior",
        industries: "",
        linkedin: "",
        experienceStarted: "20/5/25",
        joinedCieden: "",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Olha",
        lastName: "Shvets",
        email: "olha.shvets@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Middle",
        industries: "",
        linkedin: "https://www.linkedin.com/in/olha-shvets/",
        experienceStarted: "1/1/21",
        joinedCieden: "9/6/25",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Roman",
        lastName: "Kaminechny",
        email: "roman.kaminechny@cieden.com",
        role: "Leader",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Yurii Mykhasyak",
        access: "Leader",
        cv: "",
        seniority: "Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/kaminechny",
        experienceStarted: "10/1/2012",
        joinedCieden: "10/6/20",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Tetiana",
        lastName: "Zakus",
        email: "tetiana.zakus@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "https://drive.google.com/file/d/1WXsE1RwMzSAT2RbXHiZqh7APUFAkb-eP/view?usp=drive_link",
        seniority: "Str. Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/tanya-zakus",
        experienceStarted: "9/1/17",
        joinedCieden: "24/9/20",
        inCieden: "",
        totalExperience: "",
        english: "B1",
        isActive: true,
      },
      {
        firstName: "Valentyn",
        lastName: "Skliarov",
        email: "valentyn.skliarov@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Senior",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/valentyn-skliarov",
        experienceStarted: "1/2/18",
        joinedCieden: "1/11/18",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Valeria",
        lastName: "Nasikan",
        email: "valeriia.nasikan@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Str. Middle",
        industries: "",
        linkedin: "",
        experienceStarted: "1/11/16",
        joinedCieden: "27/12/24",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Vladyslav",
        lastName: "Pianov",
        email: "vladyslav.pianov@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "Str. Middle",
        industries: "",
        linkedin: "",
        experienceStarted: "2017",
        joinedCieden: "8/4/24",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Volodymyr",
        lastName: "Merlenko",
        email: "volodymyr.merlenko@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Anastasiya Mudryk",
        access: "Employee",
        cv: "https://drive.google.com/file/d/1465dQJsrxcsQkUmW2NeraKfGUuTT1hEr/view?usp=drive_link",
        seniority: "Str. Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/merlenkov",
        experienceStarted: "1/12/21",
        joinedCieden: "22/5/23",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Yuliia",
        lastName: "Braslavska",
        email: "yuliia.braslavska@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Olesia Havryshko",
        access: "Employee",
        cv: "https://drive.google.com/file/d/1h-1x0QOI3s_6zChrdRgKtsGilGe2Dz9I/view?usp=drive_link",
        seniority: "Middle",
        industries: "",
        linkedin: "https://ua.linkedin.com/in/yuliabraslavska",
        experienceStarted: "9/1/18",
        joinedCieden: "16/11/21",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Tanya",
        lastName: "Borysenko",
        email: "tanya.borysenko@cieden.com",
        role: "employee",
        department: "Design",
        position: "UX/UI Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Roman Kaminechny",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "",
        joinedCieden: "",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Anastasiya",
        lastName: "Mudryk",
        email: "anastasiya.mudryk@cieden.com",
        role: "Leader",
        department: "Product",
        position: "Product Manager/Business Analyst",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Yurii Mykhasyak",
        access: "Leader",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/11/18",
        joinedCieden: "1/11/18",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Olesia",
        lastName: "Havryshko",
        email: "olesia.havryshko@cieden.com",
        role: "Leader",
        department: "Product",
        position: "Product Manager/Business Analyst",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Anastasiya Mudryk",
        access: "Leader",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/8/16",
        joinedCieden: "2/11/20",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Tetiana",
        lastName: "Bondarchuk",
        email: "tetiana.bondarchuk@cieden.com",
        role: "Leader",
        department: "Product",
        position: "Product Manager/Business Analyst",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Anastasiya Mudryk",
        access: "Leader",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/11/20",
        joinedCieden: "2/8/22",
        inCieden: "",
        totalExperience: "",
        english: "C1",
        isActive: true,
      },
      {
        firstName: "Yuliia",
        lastName: "Mahera",
        email: "yulia.mahera@cieden.com",
        role: "Leader",
        department: "Product",
        position: "Product Manager/Business Analyst",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Anastasiya Mudryk",
        access: "Leader",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/5/21",
        joinedCieden: "13/1/25",
        inCieden: "",
        totalExperience: "",
        english: "C1",
        isActive: true,
      },
      {
        firstName: "Nataliia",
        lastName: "Levko",
        email: "nataliia.levko@cieden.com",
        role: "Leader",
        department: "Finance",
        position: "Finance Manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Yurii Mykhasyak",
        access: "Leader",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/4/12",
        joinedCieden: "19/5/2025",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Nataliia",
        lastName: "Antonyshyn",
        email: "nataliia.antonyshyn@cieden.com",
        role: "employee",
        department: "Finance",
        position: "Аccountant",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Nataliia Levko",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "",
        joinedCieden: "27/9/21",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Kristina",
        lastName: "Shkriabina",
        email: "krystyna.shkriabina@cieden.com",
        role: "Leader",
        department: "Marketing",
        position: "Marketing Manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Yurii Mykhasyak",
        access: "Leader",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/12/21",
        joinedCieden: "18/9/23",
        inCieden: "",
        totalExperience: "",
        english: "C1",
        isActive: true,
      },
      {
        firstName: "Tetiana",
        lastName: "Korol",
        email: "tetiana.korol@cieden.com",
        role: "employee",
        department: "Marketing",
        position: "SMM-manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Kristina Shkriabina",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/9/20",
        joinedCieden: "13/3/24",
        inCieden: "",
        totalExperience: "",
        english: "B1",
        isActive: true,
      },
      {
        firstName: "Tamara",
        lastName: "Zhostka",
        email: "tamara.zhostka@cieden.com",
        role: "employee",
        department: "Marketing",
        position: "Content Marketing Manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Kristina Shkriabina",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/1/20",
        joinedCieden: "7/8/23",
        inCieden: "",
        totalExperience: "",
        english: "C1",
        isActive: true,
      },
      {
        firstName: "Diana",
        lastName: "Danyliv",
        email: "diana.danyliv@cieden.com",
        role: "employee",
        department: "Marketing",
        position: "Graphic Designer",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Kristina Shkriabina",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/12/20",
        joinedCieden: "4/3/24",
        inCieden: "",
        totalExperience: "",
        english: "B1",
        isActive: true,
      },
      {
        firstName: "Kateryna",
        lastName: "Zavertailo",
        email: "kateryna.zavertailo@cieden.com",
        role: "Leader",
        department: "Sales",
        position: "Sales Manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Yurii Mykhasyak",
        access: "Leader",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/12/21",
        joinedCieden: "20/1/25",
        inCieden: "",
        totalExperience: "",
        english: "C1",
        isActive: true,
      },
      {
        firstName: "Bohdana",
        lastName: "Levochko",
        email: "bohdana.levochko@cieden.com",
        role: "employee",
        department: "Sales",
        position: "Lead Generation/Account Manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Kateryna Zavertailo",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "24/7/23",
        joinedCieden: "24/7/23",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Viktoriia",
        lastName: "Boichuk",
        email: "viktoriia.boichuk@cieden.com",
        role: "employee",
        department: "Sales",
        position: "Lead Generation Manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "Kateryna Zavertailo",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/6/22",
        joinedCieden: "27/5/24",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Olha",
        lastName: "Kubrak",
        email: "olha.kubrak@cieden.com",
        role: "employee",
        department: "Talent Management",
        position: "Office manager/Event manager",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "12/12/22",
        joinedCieden: "12/12/22",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Iryna",
        lastName: "Mykhasiak",
        email: "iryna.mykhasyak@cieden.com",
        role: "employee",
        department: "Talent Management",
        position: "Recruiter",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "",
        access: "Employee",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "2/2/21",
        joinedCieden: "5/7/21",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
      {
        firstName: "Katya",
        lastName: "Gorodova",
        email: "kateryna.gorodova@cieden.com",
        role: "Admin",
        department: "Talent Management",
        position: "Head of Talent Management",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "",
        access: "Admin",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "1/4/15",
        joinedCieden: "13/9/24",
        inCieden: "",
        totalExperience: "",
        english: "B2",
        isActive: true,
      },
      {
        firstName: "Yurii",
        lastName: "Mykhasyak",
        email: "yuriy.mykhasyak@cieden.com",
        role: "Admin",
        department: "CEO",
        position: "C-level",
        hireDate: "2024-01-01",
        avatar: "",
        leader: "",
        access: "Admin",
        cv: "",
        seniority: "",
        industries: "",
        linkedin: "",
        experienceStarted: "",
        joinedCieden: "",
        inCieden: "",
        totalExperience: "",
        english: "",
        isActive: true,
      },
    ];

    // Insert all team members
    for (const member of realCiedenTeam) {
      await ctx.db.insert("users", {
        ...member,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });
    }

    return { success: true, count: realCiedenTeam.length };
  },
});
